swagger: "2.0"
info:
  title: Isis API
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /python/similar-projects/{project_name}:
    get:
      tags: ['Python']
      x-swagger-router-controller: isis.api_v1
      operationId: get_python_similar_projects
      summary: Get similar projects to the given project.
      parameters:
        - name: project_name
          in: path
          type: string
          description: Name of the project which should be checked for performance impact.
          required: true
        - name: count
          in: query
          required: false
          type: integer
          description: Number of similar projects that should be returned.
      responses:
        200:
          description: A list of similar projects to the requested one.

  /python/performance-impact/{project_name}:
    get:
      tags: ['Python']
      x-swagger-router-controller: isis.api_v1
      operationId: get_python_performance_impact
      summary: Check if the given project can have any performance impact.
      parameters:
        - name: project_name
          in: path
          type: string
          description: Name of the project which should be checked for performance impact.
          required: true
      responses:
        200:
          description: Performance impact score for the given project.

  /python/list-projects:
    get:
      tags: ['Python']
      x-swagger-router-controller: isis.api_v1
      operationId: get_python_list_projects
      summary: List projects for Python ecosystem.
      parameters:
        - name: prefix
          in: query
          type: string
          description: List projects based on prefix.
          required: false
      responses:
        200:
          description: Projects listing for Python ecosystem
